TRAIN:
    model: resnetv2sn101
    workers: 8
    batch_size: 32
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.0001

    using_moving_average : True

    print_freq: 10
    model_dir: checkpoint/resnetv2sn101_cosine

TEST:
    checkpoint_path : data/pretrained_model/ResNet101v2+SN(8,32).pth
