TRAIN:
    model: resnet_v1_152
    workers: 6
    batch_size: 32
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.0001
    pretrained: True

    f: tensorflow # input framework $ using mmdownload
    n: resnet_v1_152 # input file name $ using mmdownload
    srcFramework: tensorflow # input framework $ using mmconvert

    dstFramework: pytorch # output framework





    print_freq: 10
    model_dir: checkpoint/resnet_v1_152

TEST:
    checkpoint_path : data/resnet_v1_152.pth
