TRAIN:
    model: resnet_v2_152
    workers: 8
    batch_size: 64
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0
    #lr_mode : step
    #base_lr: 0.1
    #decay_factor : 0.1
    #step : 30,60,90
    momentum: 0.9
    weight_decay: 0.0001
    pretrained: True

    f: tensorflow # input framework $ using mmdownload
    n: resnet_v2_152 # input file name $ using mmdownload
    sf: tensorflow # input framework $ using mmconvert
    in: imagenet_resnet_v2_152.ckpt.meta #input architecture file
    iw: imagenet_resnet_v2_152.ckpt #input data file
    dstNodeName: MMdnn_Output
    df: pytorch # output framework
    om: resnet_v2_152.pth # output weight




    print_freq: 10
    model_dir: checkpoint/vgg

TEST:
    checkpoint_path : data/vgg-77.49.pth
