import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

__weights_dict = dict()

def load_weights(weight_file):
    if weight_file == None:
        return

    try:
        weights_dict = np.load(weight_file).item()
    except:
        weights_dict = np.load(weight_file, encoding='bytes').item()

    return weights_dict

class KitModel(nn.Module):

    
    def __init__(self, weight_file):
        super(KitModel, self).__init__()
        global __weights_dict
        __weights_dict = load_weights(weight_file)

        self.MobilenetV2_Conv_Conv2D = self.__conv(2, name='MobilenetV2/Conv/Conv2D', in_channels=3, out_channels=32, kernel_size=(3, 3), stride=(2, 2), groups=1, bias=None)
        self.MobilenetV2_Conv_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/Conv/BatchNorm/FusedBatchNorm', num_features=32, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv/depthwise/depthwise', in_channels=32, out_channels=32, kernel_size=(3, 3), stride=(1, 1), groups=32, bias=None)
        self.MobilenetV2_expanded_conv_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm', num_features=32, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv/project/Conv2D', in_channels=32, out_channels=16, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv/project/BatchNorm/FusedBatchNorm', num_features=16, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_1_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_1/expand/Conv2D', in_channels=16, out_channels=96, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_1_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNorm', num_features=96, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_1_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_1/depthwise/depthwise', in_channels=96, out_channels=96, kernel_size=(3, 3), stride=(2, 2), groups=96, bias=None)
        self.MobilenetV2_expanded_conv_1_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_1/depthwise/BatchNorm/FusedBatchNorm', num_features=96, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_1_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_1/project/Conv2D', in_channels=96, out_channels=24, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_1_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_1/project/BatchNorm/FusedBatchNorm', num_features=24, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_2_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_2/expand/Conv2D', in_channels=24, out_channels=144, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_2_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNorm', num_features=144, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_2_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_2/depthwise/depthwise', in_channels=144, out_channels=144, kernel_size=(3, 3), stride=(1, 1), groups=144, bias=None)
        self.MobilenetV2_expanded_conv_2_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_2/depthwise/BatchNorm/FusedBatchNorm', num_features=144, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_2_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_2/project/Conv2D', in_channels=144, out_channels=24, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_2_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_2/project/BatchNorm/FusedBatchNorm', num_features=24, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_3_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_3/expand/Conv2D', in_channels=24, out_channels=144, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_3_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_3/expand/BatchNorm/FusedBatchNorm', num_features=144, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_3_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_3/depthwise/depthwise', in_channels=144, out_channels=144, kernel_size=(3, 3), stride=(2, 2), groups=144, bias=None)
        self.MobilenetV2_expanded_conv_3_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_3/depthwise/BatchNorm/FusedBatchNorm', num_features=144, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_3_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_3/project/Conv2D', in_channels=144, out_channels=32, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_3_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_3/project/BatchNorm/FusedBatchNorm', num_features=32, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_4_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_4/expand/Conv2D', in_channels=32, out_channels=192, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_4_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_4_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_4/depthwise/depthwise', in_channels=192, out_channels=192, kernel_size=(3, 3), stride=(1, 1), groups=192, bias=None)
        self.MobilenetV2_expanded_conv_4_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_4/depthwise/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_4_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_4/project/Conv2D', in_channels=192, out_channels=32, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_4_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_4/project/BatchNorm/FusedBatchNorm', num_features=32, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_5_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_5/expand/Conv2D', in_channels=32, out_channels=192, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_5_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_5_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_5/depthwise/depthwise', in_channels=192, out_channels=192, kernel_size=(3, 3), stride=(1, 1), groups=192, bias=None)
        self.MobilenetV2_expanded_conv_5_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_5/depthwise/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_5_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_5/project/Conv2D', in_channels=192, out_channels=32, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_5_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_5/project/BatchNorm/FusedBatchNorm', num_features=32, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_6_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_6/expand/Conv2D', in_channels=32, out_channels=192, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_6_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_6_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_6/depthwise/depthwise', in_channels=192, out_channels=192, kernel_size=(3, 3), stride=(2, 2), groups=192, bias=None)
        self.MobilenetV2_expanded_conv_6_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_6/depthwise/BatchNorm/FusedBatchNorm', num_features=192, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_6_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_6/project/Conv2D', in_channels=192, out_channels=64, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_6_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_6/project/BatchNorm/FusedBatchNorm', num_features=64, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_7_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_7/expand/Conv2D', in_channels=64, out_channels=384, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_7_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_7/expand/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_7_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_7/depthwise/depthwise', in_channels=384, out_channels=384, kernel_size=(3, 3), stride=(1, 1), groups=384, bias=None)
        self.MobilenetV2_expanded_conv_7_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_7/depthwise/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_7_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_7/project/Conv2D', in_channels=384, out_channels=64, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_7_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_7/project/BatchNorm/FusedBatchNorm', num_features=64, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_8_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_8/expand/Conv2D', in_channels=64, out_channels=384, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_8_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_8/expand/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_8_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_8/depthwise/depthwise', in_channels=384, out_channels=384, kernel_size=(3, 3), stride=(1, 1), groups=384, bias=None)
        self.MobilenetV2_expanded_conv_8_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_8/depthwise/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_8_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_8/project/Conv2D', in_channels=384, out_channels=64, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_8_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_8/project/BatchNorm/FusedBatchNorm', num_features=64, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_9_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_9/expand/Conv2D', in_channels=64, out_channels=384, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_9_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_9/expand/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_9_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_9/depthwise/depthwise', in_channels=384, out_channels=384, kernel_size=(3, 3), stride=(1, 1), groups=384, bias=None)
        self.MobilenetV2_expanded_conv_9_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_9/depthwise/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_9_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_9/project/Conv2D', in_channels=384, out_channels=64, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_9_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_9/project/BatchNorm/FusedBatchNorm', num_features=64, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_10_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_10/expand/Conv2D', in_channels=64, out_channels=384, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_10_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_10/expand/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_10_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_10/depthwise/depthwise', in_channels=384, out_channels=384, kernel_size=(3, 3), stride=(1, 1), groups=384, bias=None)
        self.MobilenetV2_expanded_conv_10_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_10/depthwise/BatchNorm/FusedBatchNorm', num_features=384, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_10_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_10/project/Conv2D', in_channels=384, out_channels=96, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_10_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_10/project/BatchNorm/FusedBatchNorm', num_features=96, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_11_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_11/expand/Conv2D', in_channels=96, out_channels=576, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_11_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_11/expand/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_11_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_11/depthwise/depthwise', in_channels=576, out_channels=576, kernel_size=(3, 3), stride=(1, 1), groups=576, bias=None)
        self.MobilenetV2_expanded_conv_11_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_11/depthwise/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_11_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_11/project/Conv2D', in_channels=576, out_channels=96, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_11_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_11/project/BatchNorm/FusedBatchNorm', num_features=96, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_12_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_12/expand/Conv2D', in_channels=96, out_channels=576, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_12_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_12/expand/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_12_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_12/depthwise/depthwise', in_channels=576, out_channels=576, kernel_size=(3, 3), stride=(1, 1), groups=576, bias=None)
        self.MobilenetV2_expanded_conv_12_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_12/depthwise/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_12_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_12/project/Conv2D', in_channels=576, out_channels=96, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_12_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_12/project/BatchNorm/FusedBatchNorm', num_features=96, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_13_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_13/expand/Conv2D', in_channels=96, out_channels=576, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_13_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_13/expand/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_13_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_13/depthwise/depthwise', in_channels=576, out_channels=576, kernel_size=(3, 3), stride=(2, 2), groups=576, bias=None)
        self.MobilenetV2_expanded_conv_13_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_13/depthwise/BatchNorm/FusedBatchNorm', num_features=576, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_13_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_13/project/Conv2D', in_channels=576, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_13_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_13/project/BatchNorm/FusedBatchNorm', num_features=160, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_14_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_14/expand/Conv2D', in_channels=160, out_channels=960, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_14_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_14/expand/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_14_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_14/depthwise/depthwise', in_channels=960, out_channels=960, kernel_size=(3, 3), stride=(1, 1), groups=960, bias=None)
        self.MobilenetV2_expanded_conv_14_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_14/depthwise/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_14_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_14/project/Conv2D', in_channels=960, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_14_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_14/project/BatchNorm/FusedBatchNorm', num_features=160, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_15_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_15/expand/Conv2D', in_channels=160, out_channels=960, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_15_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_15/expand/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_15_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_15/depthwise/depthwise', in_channels=960, out_channels=960, kernel_size=(3, 3), stride=(1, 1), groups=960, bias=None)
        self.MobilenetV2_expanded_conv_15_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_15/depthwise/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_15_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_15/project/Conv2D', in_channels=960, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_15_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_15/project/BatchNorm/FusedBatchNorm', num_features=160, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_16_expand_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_16/expand/Conv2D', in_channels=160, out_channels=960, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_16_expand_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_16/expand/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_16_depthwise_depthwise = self.__conv(2, name='MobilenetV2/expanded_conv_16/depthwise/depthwise', in_channels=960, out_channels=960, kernel_size=(3, 3), stride=(1, 1), groups=960, bias=None)
        self.MobilenetV2_expanded_conv_16_depthwise_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_16/depthwise/BatchNorm/FusedBatchNorm', num_features=960, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_expanded_conv_16_project_Conv2D = self.__conv(2, name='MobilenetV2/expanded_conv_16/project/Conv2D', in_channels=960, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_expanded_conv_16_project_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/expanded_conv_16/project/BatchNorm/FusedBatchNorm', num_features=320, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_Conv_1_Conv2D = self.__conv(2, name='MobilenetV2/Conv_1/Conv2D', in_channels=320, out_channels=1280, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=None)
        self.MobilenetV2_Conv_1_BatchNorm_FusedBatchNorm = self.__batch_normalization(2, 'MobilenetV2/Conv_1/BatchNorm/FusedBatchNorm', num_features=1280, eps=0.0010000000474974513, momentum=0.0)
        self.MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D = self.__conv(2, name='MobilenetV2/Logits/Conv2d_1c_1x1/Conv2D', in_channels=1280, out_channels=1001, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=True)

    def forward(self, x):
        MobilenetV2_Conv_Conv2D_pad = F.pad(x, (0, 1, 0, 1))
        MobilenetV2_Conv_Conv2D = self.MobilenetV2_Conv_Conv2D(MobilenetV2_Conv_Conv2D_pad)
        MobilenetV2_Conv_BatchNorm_FusedBatchNorm = self.MobilenetV2_Conv_BatchNorm_FusedBatchNorm(MobilenetV2_Conv_Conv2D)
        MobilenetV2_Conv_Relu6 = F.relu6(MobilenetV2_Conv_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_depthwise_depthwise_pad = F.pad(MobilenetV2_Conv_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_depthwise_depthwise = self.MobilenetV2_expanded_conv_depthwise_depthwise(MobilenetV2_expanded_conv_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_depthwise_depthwise)
        MobilenetV2_expanded_conv_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_project_Conv2D = self.MobilenetV2_expanded_conv_project_Conv2D(MobilenetV2_expanded_conv_depthwise_Relu6)
        MobilenetV2_expanded_conv_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_project_Conv2D)
        MobilenetV2_expanded_conv_1_expand_Conv2D = self.MobilenetV2_expanded_conv_1_expand_Conv2D(MobilenetV2_expanded_conv_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_1_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_1_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_1_expand_Conv2D)
        MobilenetV2_expanded_conv_1_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_1_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_1_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_1_expand_Relu6, (0, 1, 0, 1))
        MobilenetV2_expanded_conv_1_depthwise_depthwise = self.MobilenetV2_expanded_conv_1_depthwise_depthwise(MobilenetV2_expanded_conv_1_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_1_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_1_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_1_depthwise_depthwise)
        MobilenetV2_expanded_conv_1_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_1_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_1_project_Conv2D = self.MobilenetV2_expanded_conv_1_project_Conv2D(MobilenetV2_expanded_conv_1_depthwise_Relu6)
        MobilenetV2_expanded_conv_1_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_1_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_1_project_Conv2D)
        MobilenetV2_expanded_conv_2_expand_Conv2D = self.MobilenetV2_expanded_conv_2_expand_Conv2D(MobilenetV2_expanded_conv_1_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_2_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_2_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_2_expand_Conv2D)
        MobilenetV2_expanded_conv_2_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_2_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_2_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_2_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_2_depthwise_depthwise = self.MobilenetV2_expanded_conv_2_depthwise_depthwise(MobilenetV2_expanded_conv_2_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_2_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_2_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_2_depthwise_depthwise)
        MobilenetV2_expanded_conv_2_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_2_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_2_project_Conv2D = self.MobilenetV2_expanded_conv_2_project_Conv2D(MobilenetV2_expanded_conv_2_depthwise_Relu6)
        MobilenetV2_expanded_conv_2_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_2_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_2_project_Conv2D)
        MobilenetV2_expanded_conv_2_add = MobilenetV2_expanded_conv_2_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_1_project_BatchNorm_FusedBatchNorm
        MobilenetV2_expanded_conv_3_expand_Conv2D = self.MobilenetV2_expanded_conv_3_expand_Conv2D(MobilenetV2_expanded_conv_2_add)
        MobilenetV2_expanded_conv_3_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_3_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_3_expand_Conv2D)
        MobilenetV2_expanded_conv_3_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_3_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_3_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_3_expand_Relu6, (0, 1, 0, 1))
        MobilenetV2_expanded_conv_3_depthwise_depthwise = self.MobilenetV2_expanded_conv_3_depthwise_depthwise(MobilenetV2_expanded_conv_3_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_3_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_3_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_3_depthwise_depthwise)
        MobilenetV2_expanded_conv_3_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_3_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_3_project_Conv2D = self.MobilenetV2_expanded_conv_3_project_Conv2D(MobilenetV2_expanded_conv_3_depthwise_Relu6)
        MobilenetV2_expanded_conv_3_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_3_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_3_project_Conv2D)
        MobilenetV2_expanded_conv_4_expand_Conv2D = self.MobilenetV2_expanded_conv_4_expand_Conv2D(MobilenetV2_expanded_conv_3_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_4_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_4_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_4_expand_Conv2D)
        MobilenetV2_expanded_conv_4_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_4_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_4_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_4_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_4_depthwise_depthwise = self.MobilenetV2_expanded_conv_4_depthwise_depthwise(MobilenetV2_expanded_conv_4_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_4_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_4_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_4_depthwise_depthwise)
        MobilenetV2_expanded_conv_4_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_4_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_4_project_Conv2D = self.MobilenetV2_expanded_conv_4_project_Conv2D(MobilenetV2_expanded_conv_4_depthwise_Relu6)
        MobilenetV2_expanded_conv_4_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_4_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_4_project_Conv2D)
        MobilenetV2_expanded_conv_4_add = MobilenetV2_expanded_conv_4_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_3_project_BatchNorm_FusedBatchNorm
        MobilenetV2_expanded_conv_5_expand_Conv2D = self.MobilenetV2_expanded_conv_5_expand_Conv2D(MobilenetV2_expanded_conv_4_add)
        MobilenetV2_expanded_conv_5_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_5_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_5_expand_Conv2D)
        MobilenetV2_expanded_conv_5_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_5_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_5_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_5_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_5_depthwise_depthwise = self.MobilenetV2_expanded_conv_5_depthwise_depthwise(MobilenetV2_expanded_conv_5_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_5_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_5_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_5_depthwise_depthwise)
        MobilenetV2_expanded_conv_5_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_5_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_5_project_Conv2D = self.MobilenetV2_expanded_conv_5_project_Conv2D(MobilenetV2_expanded_conv_5_depthwise_Relu6)
        MobilenetV2_expanded_conv_5_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_5_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_5_project_Conv2D)
        MobilenetV2_expanded_conv_5_add = MobilenetV2_expanded_conv_5_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_4_add
        MobilenetV2_expanded_conv_6_expand_Conv2D = self.MobilenetV2_expanded_conv_6_expand_Conv2D(MobilenetV2_expanded_conv_5_add)
        MobilenetV2_expanded_conv_6_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_6_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_6_expand_Conv2D)
        MobilenetV2_expanded_conv_6_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_6_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_6_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_6_expand_Relu6, (0, 1, 0, 1))
        MobilenetV2_expanded_conv_6_depthwise_depthwise = self.MobilenetV2_expanded_conv_6_depthwise_depthwise(MobilenetV2_expanded_conv_6_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_6_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_6_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_6_depthwise_depthwise)
        MobilenetV2_expanded_conv_6_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_6_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_6_project_Conv2D = self.MobilenetV2_expanded_conv_6_project_Conv2D(MobilenetV2_expanded_conv_6_depthwise_Relu6)
        MobilenetV2_expanded_conv_6_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_6_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_6_project_Conv2D)
        MobilenetV2_expanded_conv_7_expand_Conv2D = self.MobilenetV2_expanded_conv_7_expand_Conv2D(MobilenetV2_expanded_conv_6_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_7_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_7_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_7_expand_Conv2D)
        MobilenetV2_expanded_conv_7_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_7_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_7_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_7_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_7_depthwise_depthwise = self.MobilenetV2_expanded_conv_7_depthwise_depthwise(MobilenetV2_expanded_conv_7_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_7_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_7_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_7_depthwise_depthwise)
        MobilenetV2_expanded_conv_7_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_7_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_7_project_Conv2D = self.MobilenetV2_expanded_conv_7_project_Conv2D(MobilenetV2_expanded_conv_7_depthwise_Relu6)
        MobilenetV2_expanded_conv_7_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_7_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_7_project_Conv2D)
        MobilenetV2_expanded_conv_7_add = MobilenetV2_expanded_conv_7_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_6_project_BatchNorm_FusedBatchNorm
        MobilenetV2_expanded_conv_8_expand_Conv2D = self.MobilenetV2_expanded_conv_8_expand_Conv2D(MobilenetV2_expanded_conv_7_add)
        MobilenetV2_expanded_conv_8_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_8_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_8_expand_Conv2D)
        MobilenetV2_expanded_conv_8_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_8_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_8_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_8_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_8_depthwise_depthwise = self.MobilenetV2_expanded_conv_8_depthwise_depthwise(MobilenetV2_expanded_conv_8_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_8_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_8_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_8_depthwise_depthwise)
        MobilenetV2_expanded_conv_8_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_8_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_8_project_Conv2D = self.MobilenetV2_expanded_conv_8_project_Conv2D(MobilenetV2_expanded_conv_8_depthwise_Relu6)
        MobilenetV2_expanded_conv_8_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_8_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_8_project_Conv2D)
        MobilenetV2_expanded_conv_8_add = MobilenetV2_expanded_conv_8_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_7_add
        MobilenetV2_expanded_conv_9_expand_Conv2D = self.MobilenetV2_expanded_conv_9_expand_Conv2D(MobilenetV2_expanded_conv_8_add)
        MobilenetV2_expanded_conv_9_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_9_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_9_expand_Conv2D)
        MobilenetV2_expanded_conv_9_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_9_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_9_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_9_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_9_depthwise_depthwise = self.MobilenetV2_expanded_conv_9_depthwise_depthwise(MobilenetV2_expanded_conv_9_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_9_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_9_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_9_depthwise_depthwise)
        MobilenetV2_expanded_conv_9_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_9_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_9_project_Conv2D = self.MobilenetV2_expanded_conv_9_project_Conv2D(MobilenetV2_expanded_conv_9_depthwise_Relu6)
        MobilenetV2_expanded_conv_9_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_9_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_9_project_Conv2D)
        MobilenetV2_expanded_conv_9_add = MobilenetV2_expanded_conv_9_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_8_add
        MobilenetV2_expanded_conv_10_expand_Conv2D = self.MobilenetV2_expanded_conv_10_expand_Conv2D(MobilenetV2_expanded_conv_9_add)
        MobilenetV2_expanded_conv_10_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_10_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_10_expand_Conv2D)
        MobilenetV2_expanded_conv_10_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_10_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_10_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_10_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_10_depthwise_depthwise = self.MobilenetV2_expanded_conv_10_depthwise_depthwise(MobilenetV2_expanded_conv_10_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_10_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_10_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_10_depthwise_depthwise)
        MobilenetV2_expanded_conv_10_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_10_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_10_project_Conv2D = self.MobilenetV2_expanded_conv_10_project_Conv2D(MobilenetV2_expanded_conv_10_depthwise_Relu6)
        MobilenetV2_expanded_conv_10_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_10_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_10_project_Conv2D)
        MobilenetV2_expanded_conv_11_expand_Conv2D = self.MobilenetV2_expanded_conv_11_expand_Conv2D(MobilenetV2_expanded_conv_10_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_11_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_11_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_11_expand_Conv2D)
        MobilenetV2_expanded_conv_11_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_11_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_11_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_11_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_11_depthwise_depthwise = self.MobilenetV2_expanded_conv_11_depthwise_depthwise(MobilenetV2_expanded_conv_11_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_11_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_11_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_11_depthwise_depthwise)
        MobilenetV2_expanded_conv_11_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_11_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_11_project_Conv2D = self.MobilenetV2_expanded_conv_11_project_Conv2D(MobilenetV2_expanded_conv_11_depthwise_Relu6)
        MobilenetV2_expanded_conv_11_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_11_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_11_project_Conv2D)
        MobilenetV2_expanded_conv_11_add = MobilenetV2_expanded_conv_11_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_10_project_BatchNorm_FusedBatchNorm
        MobilenetV2_expanded_conv_12_expand_Conv2D = self.MobilenetV2_expanded_conv_12_expand_Conv2D(MobilenetV2_expanded_conv_11_add)
        MobilenetV2_expanded_conv_12_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_12_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_12_expand_Conv2D)
        MobilenetV2_expanded_conv_12_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_12_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_12_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_12_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_12_depthwise_depthwise = self.MobilenetV2_expanded_conv_12_depthwise_depthwise(MobilenetV2_expanded_conv_12_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_12_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_12_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_12_depthwise_depthwise)
        MobilenetV2_expanded_conv_12_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_12_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_12_project_Conv2D = self.MobilenetV2_expanded_conv_12_project_Conv2D(MobilenetV2_expanded_conv_12_depthwise_Relu6)
        MobilenetV2_expanded_conv_12_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_12_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_12_project_Conv2D)
        MobilenetV2_expanded_conv_12_add = MobilenetV2_expanded_conv_12_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_11_add
        MobilenetV2_expanded_conv_13_expand_Conv2D = self.MobilenetV2_expanded_conv_13_expand_Conv2D(MobilenetV2_expanded_conv_12_add)
        MobilenetV2_expanded_conv_13_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_13_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_13_expand_Conv2D)
        MobilenetV2_expanded_conv_13_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_13_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_13_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_13_expand_Relu6, (0, 1, 0, 1))
        MobilenetV2_expanded_conv_13_depthwise_depthwise = self.MobilenetV2_expanded_conv_13_depthwise_depthwise(MobilenetV2_expanded_conv_13_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_13_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_13_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_13_depthwise_depthwise)
        MobilenetV2_expanded_conv_13_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_13_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_13_project_Conv2D = self.MobilenetV2_expanded_conv_13_project_Conv2D(MobilenetV2_expanded_conv_13_depthwise_Relu6)
        MobilenetV2_expanded_conv_13_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_13_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_13_project_Conv2D)
        MobilenetV2_expanded_conv_14_expand_Conv2D = self.MobilenetV2_expanded_conv_14_expand_Conv2D(MobilenetV2_expanded_conv_13_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_14_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_14_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_14_expand_Conv2D)
        MobilenetV2_expanded_conv_14_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_14_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_14_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_14_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_14_depthwise_depthwise = self.MobilenetV2_expanded_conv_14_depthwise_depthwise(MobilenetV2_expanded_conv_14_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_14_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_14_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_14_depthwise_depthwise)
        MobilenetV2_expanded_conv_14_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_14_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_14_project_Conv2D = self.MobilenetV2_expanded_conv_14_project_Conv2D(MobilenetV2_expanded_conv_14_depthwise_Relu6)
        MobilenetV2_expanded_conv_14_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_14_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_14_project_Conv2D)
        MobilenetV2_expanded_conv_14_add = MobilenetV2_expanded_conv_14_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_13_project_BatchNorm_FusedBatchNorm
        MobilenetV2_expanded_conv_15_expand_Conv2D = self.MobilenetV2_expanded_conv_15_expand_Conv2D(MobilenetV2_expanded_conv_14_add)
        MobilenetV2_expanded_conv_15_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_15_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_15_expand_Conv2D)
        MobilenetV2_expanded_conv_15_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_15_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_15_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_15_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_15_depthwise_depthwise = self.MobilenetV2_expanded_conv_15_depthwise_depthwise(MobilenetV2_expanded_conv_15_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_15_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_15_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_15_depthwise_depthwise)
        MobilenetV2_expanded_conv_15_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_15_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_15_project_Conv2D = self.MobilenetV2_expanded_conv_15_project_Conv2D(MobilenetV2_expanded_conv_15_depthwise_Relu6)
        MobilenetV2_expanded_conv_15_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_15_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_15_project_Conv2D)
        MobilenetV2_expanded_conv_15_add = MobilenetV2_expanded_conv_15_project_BatchNorm_FusedBatchNorm + MobilenetV2_expanded_conv_14_add
        MobilenetV2_expanded_conv_16_expand_Conv2D = self.MobilenetV2_expanded_conv_16_expand_Conv2D(MobilenetV2_expanded_conv_15_add)
        MobilenetV2_expanded_conv_16_expand_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_16_expand_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_16_expand_Conv2D)
        MobilenetV2_expanded_conv_16_expand_Relu6 = F.relu6(MobilenetV2_expanded_conv_16_expand_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_16_depthwise_depthwise_pad = F.pad(MobilenetV2_expanded_conv_16_expand_Relu6, (1, 1, 1, 1))
        MobilenetV2_expanded_conv_16_depthwise_depthwise = self.MobilenetV2_expanded_conv_16_depthwise_depthwise(MobilenetV2_expanded_conv_16_depthwise_depthwise_pad)
        MobilenetV2_expanded_conv_16_depthwise_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_16_depthwise_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_16_depthwise_depthwise)
        MobilenetV2_expanded_conv_16_depthwise_Relu6 = F.relu6(MobilenetV2_expanded_conv_16_depthwise_BatchNorm_FusedBatchNorm)
        MobilenetV2_expanded_conv_16_project_Conv2D = self.MobilenetV2_expanded_conv_16_project_Conv2D(MobilenetV2_expanded_conv_16_depthwise_Relu6)
        MobilenetV2_expanded_conv_16_project_BatchNorm_FusedBatchNorm = self.MobilenetV2_expanded_conv_16_project_BatchNorm_FusedBatchNorm(MobilenetV2_expanded_conv_16_project_Conv2D)
        MobilenetV2_Conv_1_Conv2D = self.MobilenetV2_Conv_1_Conv2D(MobilenetV2_expanded_conv_16_project_BatchNorm_FusedBatchNorm)
        MobilenetV2_Conv_1_BatchNorm_FusedBatchNorm = self.MobilenetV2_Conv_1_BatchNorm_FusedBatchNorm(MobilenetV2_Conv_1_Conv2D)
        MobilenetV2_Conv_1_Relu6 = F.relu6(MobilenetV2_Conv_1_BatchNorm_FusedBatchNorm)
        MobilenetV2_Logits_AvgPool = F.avg_pool2d(MobilenetV2_Conv_1_Relu6, kernel_size=(7, 7), stride=(1, 1), padding=(0,), ceil_mode=False)
        MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D = self.MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D(MobilenetV2_Logits_AvgPool)
        MobilenetV2_Logits_Squeeze = torch.squeeze(MobilenetV2_Logits_Conv2d_1c_1x1_Conv2D)
        MMdnn_Output    = torch.squeeze(MobilenetV2_Logits_Squeeze)
        return MMdnn_Output


    @staticmethod
    def __conv(dim, name, **kwargs):
        if   dim == 1:  layer = nn.Conv1d(**kwargs)
        elif dim == 2:  layer = nn.Conv2d(**kwargs)
        elif dim == 3:  layer = nn.Conv3d(**kwargs)
        else:           raise NotImplementedError()

        layer.state_dict()['weight'].copy_(torch.from_numpy(__weights_dict[name]['weights']))
        if 'bias' in __weights_dict[name]:
            layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
        return layer

    @staticmethod
    def __batch_normalization(dim, name, **kwargs):
        if   dim == 1:  layer = nn.BatchNorm1d(**kwargs)
        elif dim == 2:  layer = nn.BatchNorm2d(**kwargs)
        elif dim == 3:  layer = nn.BatchNorm3d(**kwargs)
        else:           raise NotImplementedError()

        if 'scale' in __weights_dict[name]:
            layer.state_dict()['weight'].copy_(torch.from_numpy(__weights_dict[name]['scale']))
        else:
            layer.weight.data.fill_(1)

        if 'bias' in __weights_dict[name]:
            layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
        else:
            layer.bias.data.fill_(0)

        layer.state_dict()['running_mean'].copy_(torch.from_numpy(__weights_dict[name]['mean']))
        layer.state_dict()['running_var'].copy_(torch.from_numpy(__weights_dict[name]['var']))
        return layer
